### ISSUE TITLE
Chart Page Base Structure

### ISSUE THREAD

**Issue by Soulmates2** [Soulmates2/2021F_CS492_Naver_shopping_list#7]
# 차트페이지 기본 골격 구현

## 상단 헤더
- 상품 리스트로 다시 돌아가는 기능
- 로그인 or 로그아웃 ?

## 상세 기능 설정 바
- 분야
- 기간
- 성별
- 연령

## 차트
- 자리 선정

## Collection
- 논의 필요

**Comment by xymon2** [comment]
찜기능도 시간별데이터가 필요할까요?

**Comment by Soulmates2** [comment]
{view : {total: 1, "2021-12-01 09:00": 1}}
{dibs : {total: 1, "2021-12-01 09:00": 1}}
과 같은 양식을 채택하여 해결했습니다.
